version: "3.1"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: matchgg
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
  domain:
    image: domain/match
    ports:
      - 8080:8080
    restart: always
